### ISSUE TITLE
EU Control Plane support

### ISSUE THREAD

**Issue by nmarian85** [cloudera-labs/cloudera.cloud#71]
Hello,

Was browsing a bit through the documentation and it is not clear to me if the Ansible collection supports CDP tenants in the EU Control Plane. We are now provisioning two new tenants in the EU Control Plane and would like to start provisioning stuff. Maybe I missed it in the docs. Will go meanwhile through the code :). 

@wmudge  @Chaffelson

**Comment by Chaffelson** [comment]
[Cdpy](https://github.com/cloudera-labs/cdpy/blob/eeb420a791dc9f59ed84fe2e758e96bd10e954c0/src/cdpy/common.py#L141) offers a cp_region property to set the region from 'default' to one of the others, like EU. The user must supply the exact string for the region name that is then used in the URI construction, for example, the CDPCLI resolves 'default' to `us-west-1` and constructs `us-west-1.cdp.cloudera.com` from that.

The Ansible Collection doesn't yet expose this to the user, it would end up in the module utils [here](https://github.com/cloudera-labs/cloudera.cloud/blob/main/plugins/module_utils/cdp_common.py).

We would also need to update documentation and perhaps variables where 'region' is used to provide a cloud infrastructure region, but may be easily confused with a CDP Control Plane region.

**Comment by nmarian85** [comment]
Many many thanks for the quick answer. Was looking at the CDP CP URL and in the Frankfurt EU region it is `eu-1.cdp.cloudera.com`, so I guess this is what should end up in the code.
Regarding the code changes, I see two ways: 
1. The (I guess) proper one: adding the parameter to each Ansible module and then calling the `CdpSdkBase` class with the `cp_region` parameter pre-filled with the value from the Ansible module param.
2. The quick-and-dirty-way: go with an environment variable that would (if defined) override the  `cp_region` in the function you showed. This has also the advantage that one can use the same code for provisioning in any Control Plane (a feature we will actually need until we migrate to the EU CP). Since I am going on holidays end of this week :), I will try to implement it this way for now.

**Comment by Chaffelson** [comment]
nah, what I mean is there's an option 3. where you add cp_region to the CdpModule class in the module_utils I linked above - all the collection modules use that as a base class and therefore those options are automatically available to all the child modules.
It should default to the US control plane, and the documentation should make it clear how to derive the string to supply to it - but then it's just coded in one place and can be reused everywhere per python DRY principals.

If we then add that as an environment variable export in [cloudera-deploy](https://github.com/cloudera-labs/cloudera-deploy/blob/17902a9395be55da174acda1741998443955d144/roles/cloudera_deploy/tasks/init.yml#L419), much like the other overrides, then you could set a cp_region in your definition.yml and it would be propagated for you. You could also do it within your own environment variables as you suggest, but this would be consistent with other similar top level controls.

**Comment by nmarian85** [comment]
Indeed, I did not read properly your first reply and dismissed initially the utils module since it was (still is :) ) a bit unclear for me how the parameters are built due to the inheritance process. My initial expectation was that the parameters are in one place module wise, but it is not like that as you pointed out. Anyway, I was chatting to a colleague of mine about this and he is working a bit on the code. We will try to follow your recommendation to implement it and, if we get it to work, try to do a MR. 

Many thanks for the help !

**Comment by jimright** [comment]
Hey @nmarian85 
cc) @Chaffelson 

Just to note that the `cdp_region` variable has been added to cloudera-deploy and exe previously. This allows deployment to different control plane regions when using cloudera-deploy. This is mainly used in exe to set the ARN prefix for CDP roles and doesn't touch cloudera.cloud. 

Relevant PRs were:
* https://github.com/cloudera-labs/cloudera-deploy/pull/78
* https://github.com/cloudera-labs/cloudera.exe/pull/91
