### ISSUE TITLE
CCMv2 support in EU Control Plane

### ISSUE THREAD

**Issue by nmarian85** [cloudera-labs/cloudera.cloud#72]
Hello again,

We are trying to provision the CDP environment via the Ansible collection (https://cloudera-labs.github.io/cloudera.cloud/env.html ) and failing miserably with the following error. We are using the `tunnel` option set to `true` since this is how we understood that CCM is enabled. 

```bash
FreeIpa creation operation failed. Reason: 'com.sequenceiq.cloudbreak.ccm.exception.CcmException: MinaSshdManagementService acquireMinaSshdService gRPC call failed: UNAVAILABLE: Unable to resolve host thunderhead-clusterconnectivitymanagement.thunderhead-clusterconnectivitymanagement.svc.cluster.local'
```
I will take a leap of faith and assume the following : the Ansible code wants to use (via the Python REST API) CCMv1 and this is not available in the EU Control Plane, as per https://docs.cloudera.com/cdp-public-cloud/cloud/requirements-aws/topics/cdp-control-plane-regions.html. Was looking a bit into the Python REST API to see if we could implement this ourselves https://cloudera.github.io/cdp-dev-docs/api-docs/environments/index.html#_createawsenvironmentrequest but could not see much around how to specify that even via the REST API. 
Can you please tell me if my assumption is correct ? Any ideas on how we can keep using CCM in the EU region?

**Comment by wmudge** [comment]
I believe this issue has been resolved with updates to the CDP control plane (the REST API). We will test this further and will reopen the ticket if we run into issues.
